version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2017
init:
- ps: Install-Product node $env:nodejs_version
environment:
  nodejs_version: 8
install:
- ps: >-
    npm install vsce -g


    ./gradlew clean --no-daemon
cache: C:\Users\appveyor\.gradle
build_script:
- ps: >-
    ./gradlew build updateVersions --continue --no-daemon

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    cd extension

    npm install

    vsce package

    if ($lastexitcode -eq 0) {
        echo $lastexitcode
    }
test: off
artifacts:
- path: '**/libs/*'
  name: Jars
- path: '**/*.vsix'
  name: VSIX
